### ISSUE TITLE
an apostrophe in answer prevents it from appearing as correct

### ISSUE THREAD

**Issue by Benjou** [PsyTeachR/webex#11]
I wrote a question with "wouldn't" in its answer
All answers appeared as wrong (with a red dshed frame), despite the "answer =" tag before them.

When changing to "would not", the answer appeared as right (blue frame).

I tried escaping with "wouldn\'t". Though the backslash did not show in the html file, the answer still appeared as wrong.

my version of webex is 0.9.1

**Comment by dalejbarr** [comment]
Bug has been fixed for version 0.9.2.
