### ISSUE TITLE
div class 'solution' + button conflicts with latest version of bookdown 0.21

### ISSUE THREAD

**Issue by dalejbarr** [PsyTeachR/webex#12]
as noted by @debruine [here](https://twitter.com/LisaDeBruine/status/1402311484101775369?s=20)

webex's `hide()` outputs a div with class 'solution' that contains a button. This class of div now receives special handling by the Lua filter.

possible solution: change the div class from `solution` to something more specific like `webex-solution`

**Comment by debruine** [comment]
Changed to webex-solution (all other custom classes also changed similarity)
