### ISSUE TITLE
Specify graphical parameters for solutions

### ISSUE THREAD

**Issue by dalejbarr** [PsyTeachR/webex#3]
It would be nice to make it possible for users to tweak the default graphical parameters (such as the color of the solution boxes) in some way that wouldn't require hacking into the JavaScript code / CSS file. Perhaps some parameter in the RMarkdown YAML header?

Edit: Would also be nice to style things on the fly.

**Comment by debruine** [comment]
added `widget_style(default = "red", correct = "blue")` to change default and correct colours using any CSS-compatible color notation.
