### ISSUE TITLE
Compilation fails when mcq answer contains an apostrophe

### ISSUE THREAD

**Issue by nickriches** [PsyTeachR/webex#4]
Really enjoying using the webex tool! I'm using it to make Linguistics exercises for my students. The above issue is not important, and one can work around it quite easily, but I thought I should post it. Apostrophes seem to be parsed as quotation marks.

Offending code:

`r mcq(c(answer = "contains ap`ostrophe", "text", "text"))`

**Comment by dalejbarr** [comment]
Resolved in latest release (0.9.0).

**Comment by nickriches** [comment]
Brill - thanks!
