### ISSUE TITLE
tracking the number of correct answers

### ISSUE THREAD

**Issue by bioboot** [PsyTeachR/webex#9]
I see that there is a javascript function `update_total_correct()` for potentially keeping track of the number of correct student answers (in webex.js). 

Is there any guidance (or Rmarkdown template) on how to use this to display a running total or other from of student score?

**Comment by debruine** [comment]
You just need any HTML element with the id "total_correct". I'll add a function to generate that, but for now you can add the following anywhere in the .Rmd document.

```
<div id="total_correct"></div>
```

or to make it bigger:

```
<h3 id="total_correct"></h3>
```

**Comment by debruine** [comment]
I've added a function `total_correct()` and updated the template in the development version here. It will be included in the next update to the CRAN version. Thanks!!

**Comment by bioboot** [comment]
Fantastic, thanks Lisa!
